export type PromptType = "text" | "image";

export interface Prompt {
  id: string;
  text: string;
  type: PromptType;
  source: "TINDER" | "HINGE";
  imageAttachmentId?: string; // For image-paired prompts - reference to attachment table
  category?: string; // Optional categorization
}

/**
 * To add image-paired prompts:
 * 1. Upload the prompt image to your gallery (it will create an attachment)
 * 2. Copy the attachment ID
 * 3. Add a prompt with type: "image" and include the imageAttachmentId
 *
 * Example:
 * {
 *   id: "hinge-16",
 *   text: "Two truths and a lie",
 *   type: "image",
 *   source: "HINGE",
 *   imageAttachmentId: "att_abc123xyz", // The attachment ID from your gallery
 *   category: "Humor",
 * }
 */

export const PROMPT_BANK: Record<"TINDER" | "HINGE", Prompt[]> = {
  TINDER: [
    {
      id: "tinder-1",
      text: "My simple pleasures",
      type: "text",
      source: "TINDER",
      category: "Lifestyle",
    },
    {
      id: "tinder-2",
      text: "I'm looking for",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-3",
      text: "My biggest flex",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-4",
      text: "I'm known for",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-5",
      text: "My ideal Sunday",
      type: "text",
      source: "TINDER",
      category: "Lifestyle",
    },
    {
      id: "tinder-6",
      text: "I go crazy for",
      type: "text",
      source: "TINDER",
      category: "Interests",
    },
    {
      id: "tinder-7",
      text: "A life goal of mine",
      type: "text",
      source: "TINDER",
      category: "Values",
    },
    {
      id: "tinder-8",
      text: "I'm weirdly attracted to",
      type: "text",
      source: "TINDER",
      category: "Humor",
    },
    {
      id: "tinder-9",
      text: "My most controversial opinion",
      type: "text",
      source: "TINDER",
      category: "Conversation",
    },
    {
      id: "tinder-10",
      text: "Don't hate me if I",
      type: "text",
      source: "TINDER",
      category: "Humor",
    },
    {
      id: "tinder-11",
      text: "My favorite playlist is called",
      type: "text",
      source: "TINDER",
      category: "Interests",
    },
    {
      id: "tinder-12",
      text: "A surprising thing about me is",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-13",
      text: "My biography would probably be called",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-14",
      text: "The hottest thing you can do is",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-15",
      text: "My go-to karaoke song is",
      type: "text",
      source: "TINDER",
      category: "Interests",
    },
    {
      id: "tinder-16",
      text: "My hidden talent is",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-17",
      text: "My dream job is",
      type: "text",
      source: "TINDER",
      category: "Values",
    },
    {
      id: "tinder-18",
      text: "People would describe me as",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-19",
      text: "My worst midnight snack habit",
      type: "text",
      source: "TINDER",
      category: "Humor",
    },
    {
      id: "tinder-20",
      text: "Me: I'm a grown up. Also me:",
      type: "text",
      source: "TINDER",
      category: "Humor",
    },
    {
      id: "tinder-21",
      text: "If I had 20 minutes left to live, I would",
      type: "text",
      source: "TINDER",
      category: "Values",
    },
    {
      id: "tinder-22",
      text: "First date wish list:",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-23",
      text: "Perks of dating me",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-24",
      text: "Two truths and a lie",
      type: "text",
      source: "TINDER",
      category: "Conversation",
    },
    {
      id: "tinder-25",
      text: "Message me if you also love",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-26",
      text: "My weakness is",
      type: "text",
      source: "TINDER",
      category: "Personality",
    },
    {
      id: "tinder-27",
      text: "Life's too short to",
      type: "text",
      source: "TINDER",
      category: "Values",
    },
    {
      id: "tinder-28",
      text: "My biggest red flag is",
      type: "text",
      source: "TINDER",
      category: "Humor",
    },
    {
      id: "tinder-29",
      text: "The key to my heart is",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-30",
      text: "If I'm not home, you can find me",
      type: "text",
      source: "TINDER",
      category: "Lifestyle",
    },
    {
      id: "tinder-31",
      text: "I can beat you in a game of",
      type: "text",
      source: "TINDER",
      category: "Interests",
    },
    {
      id: "tinder-32",
      text: "I want someone who",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    {
      id: "tinder-33",
      text: "My weird but true story is",
      type: "text",
      source: "TINDER",
      category: "Conversation",
    },
    {
      id: "tinder-34",
      text: "The first item on my bucket list is",
      type: "text",
      source: "TINDER",
      category: "Values",
    },
    {
      id: "tinder-35",
      text: "My parents will like you if",
      type: "text",
      source: "TINDER",
      category: "Dating",
    },
    // Photo Caption Prompts
    {
      id: "tinder-caption-1",
      text: "A favorite memory of mine",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-2",
      text: "POV: You just met me",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-3",
      text: "Just me being iconic",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-4",
      text: "Giving main character energy",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-5",
      text: "Guess where this was taken",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-6",
      text: "You can usually find me here",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-7",
      text: "The lighting has never been this good",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-8",
      text: "Me 80% of the time",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-9",
      text: "Proof I'd make a great wedding date",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-10",
      text: "Self-care Sunday vibes",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-11",
      text: "I will never be this cool again",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-12",
      text: "Guess my celebrity doppelganger",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-13",
      text: "This is my silly era",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-14",
      text: "My villain origin story",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-15",
      text: "My hero origin story",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-16",
      text: "Happy birthday to me",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-17",
      text: "My home away from home",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-18",
      text: "Costume of the century",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-19",
      text: "The picture I begged my friend to take",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-20",
      text: "Lost in the moment",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-21",
      text: "Life's a blur",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-22",
      text: "This felt cinematic at the time",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-23",
      text: "I didn't know the camera was on",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
    {
      id: "tinder-caption-24",
      text: "Biggest obsession? Here's a clue",
      type: "text",
      source: "TINDER",
      category: "Photo Captions",
    },
  ],
  HINGE: [
    {
      id: "hinge-1",
      text: "My simple pleasures",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-2",
      text: "Together we could",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-3",
      text: "I'm looking for",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-4",
      text: "My greatest strength",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-5",
      text: "Unusual skills",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-6",
      text: "I'm overly competitive about",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-7",
      text: "The key to my heart is",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-8",
      text: "I'll know I've met the one when",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-9",
      text: "Biggest risk I've taken",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-10",
      text: "I'm convinced that",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-11",
      text: "My most irrational fear",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-12",
      text: "I geek out on",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-13",
      text: "A shower thought I recently had",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-14",
      text: "The hallmark of a good relationship is",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-15",
      text: "We'll get along if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-16",
      text: "Something my pet thinks about me",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-17",
      text: "I'm in my element when",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-18",
      text: "In my friend group, I'm the one who",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-19",
      text: "It's not a vacation unless",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-20",
      text: "I could stay up all night talking about",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-21",
      text: "Where I go when I want to feel a little more like myself",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-22",
      text: "An award my family would give me",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-23",
      text: "Before we meet, you should listen to",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-24",
      text: "You'd never know it, but I",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-25",
      text: "The kindest thing someone has ever done for me",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-26",
      text: "I hype myself up by",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-27",
      text: "My cry-in-the-car song is",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-28",
      text: "To me, relaxation is",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-29",
      text: "A boundary of mine is",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-30",
      text: "My self-care routine is",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-31",
      text: "My friends ask me for advice about",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-32",
      text: "I feel most supported when",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-33",
      text: "Therapy recently taught me",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-34",
      text: "I wind down by",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-35",
      text: "When I need advice, I go to",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-36",
      text: "My therapist would say I",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-37",
      text: "I get myself out of a funk by",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-38",
      text: "My last journal entry was about",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-39",
      text: "The last time I cried happy tears was",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-40",
      text: "One thing I'll never do again",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-41",
      text: "My biggest date fail",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-42",
      text: "Best travel story",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-43",
      text: "Most spontaneous thing I've done",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-44",
      text: "Weirdest gift I have given or received",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-45",
      text: "Worst idea I've ever had",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-46",
      text: "Apparently, my life's soundtrack is",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-47",
      text: "Proof I have musical talent",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-48",
      text: "Guess the song",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-49",
      text: "A quick rant about",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-50",
      text: 'Saying "Hi!" in as many languages I know',
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-51",
      text: "I'll give you the set up, you guess the punchline",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-52",
      text: "My favorite line from a movie",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-53",
      text: "How to pronounce my name",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-54",
      text: "My BFF's take on why you should date me",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-55",
      text: "My best celebrity impression",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-56",
      text: "I wish more people knew",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-57",
      text: "My best Dad Joke",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-58",
      text: "A shower thought I recently had",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-59",
      text: "My Love Language is",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-60",
      text: "I won't shut up about",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-61",
      text: "If loving this is wrong, I don't want to be right",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-62",
      text: "You should *not* go out with me if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-63",
      text: "Don't hate me if I",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-64",
      text: "I geek out on",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-65",
      text: "The dorkiest thing about me is",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-66",
      text: "What if I told you that",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-67",
      text: "The one thing you should know about me is",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-68",
      text: "I want someone who",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-69",
      text: "Green flags I look for",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-70",
      text: "I'll brag about you to my friends if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-71",
      text: "I'm weirdly attracted to",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-72",
      text: "I'll fall for you if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-73",
      text: "Something that's non-negotiable for me is",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-74",
      text: "All I ask is that you",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-75",
      text: "The hallmark of a good relationship is",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-76",
      text: "We're the same type of weird if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-77",
      text: "It feels affirming when others",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-78",
      text: "My favorite LGBTQIA+ book is",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-79",
      text: "I connect to my community by",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-80",
      text: "I feel proudest of who I am when",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-81",
      text: "The first time I knew I was gay was",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-82",
      text: "My favorite off-brand LGBTQIA+ icon is",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-83",
      text: "My chosen family is the best at",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-84",
      text: "My favorite LGBTQIA+-owned places",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-85",
      text: "Gender euphoria looks like",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-86",
      text: "I wish I could tell the younger version of myself",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-87",
      text: "Let's debate this topic",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-88",
      text: "The one thing I'd love to know about you is",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-89",
      text: "Teach me something about",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-90",
      text: "You should leave a comment if",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-91",
      text: "Do you agree or disagree that",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-92",
      text: "Change my mind about",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-93",
      text: "I'll pick the topic if you start the conversation",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-94",
      text: "Try to guess this about me",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-95",
      text: "I bet you can't",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-96",
      text: "Give me travel tips for",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-97",
      text: "Let's make sure we're on the same page about",
      type: "text",
      source: "HINGE",
      category: "Conversation",
    },
    {
      id: "hinge-98",
      text: "My greatest strength",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-99",
      text: "I recently discovered that",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-100",
      text: "I go crazy for",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-101",
      text: "The way to win me over is",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-102",
      text: "A random fact I love is",
      type: "text",
      source: "HINGE",
      category: "Interests",
    },
    {
      id: "hinge-103",
      text: "Unusual skills",
      type: "text",
      source: "HINGE",
      category: "Personality",
    },
    {
      id: "hinge-104",
      text: "Typical Sunday",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-105",
      text: "Dating me is like",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-106",
      text: "A life goal of mine",
      type: "text",
      source: "HINGE",
      category: "Values",
    },
    {
      id: "hinge-107",
      text: "My most irrational fear",
      type: "text",
      source: "HINGE",
      category: "Humor",
    },
    {
      id: "hinge-108",
      text: "The best way to ask me out is by",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-109",
      text: "I know the best spot in town for",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-110",
      text: "What I order for the table",
      type: "text",
      source: "HINGE",
      category: "Lifestyle",
    },
    {
      id: "hinge-111",
      text: "Together, we could",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    {
      id: "hinge-112",
      text: "First round is on me if",
      type: "text",
      source: "HINGE",
      category: "Dating",
    },
    // Photo Caption Prompts
    {
      id: "hinge-caption-1",
      text: "Selfie #503",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-2",
      text: "Help me identify this photo bomber",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-3",
      text: "My life behind the scenes",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-4",
      text: "How my friends see me",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-5",
      text: "My funniest home video submission",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-6",
      text: "Get someone who looks at you like",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-7",
      text: "Dating me will look like",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-8",
      text: "My quarter life crisis looks like",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-9",
      text: "That one dance trend I nailed",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-10",
      text: "My uniform",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-11",
      text: "Felt cute might delete later",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-12",
      text: "My dog looks at me like this",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-13",
      text: "Are you a cat person because",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-14",
      text: "Life outtake",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-15",
      text: "My Instagram Story mostly contains",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-16",
      text: "Me in my blogging days",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-17",
      text: "I can teach you how to",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-18",
      text: "How history will remember me",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-19",
      text: "Together we can be terrible at",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-20",
      text: "Me in the wild",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-21",
      text: "Let's do this for our date from home",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-22",
      text: "Lowkey flex",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-23",
      text: "My best blue steel",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-24",
      text: "Never have I ever",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-25",
      text: "My good side",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-26",
      text: "Biggest risk I've ever taken",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-27",
      text: "Leave a comment if you want to meet here",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-28",
      text: "Leave a one-word review for this",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-29",
      text: "My vulnerable side",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-30",
      text: "I thought I deleted this one",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-31",
      text: "It's all about the simple things",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-32",
      text: "As seen on my Mom's fridge",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-33",
      text: "My weekends look like",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-34",
      text: "This year, I really want to",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-35",
      text: "Me during Fashion Week",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-36",
      text: "Guess the backstory of this photo",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-37",
      text: "I'm known for",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-38",
      text: "I'm learning how to",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-39",
      text: "My life peaked when",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-40",
      text: "A special talent of mine",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-41",
      text: "The moment I knew my modeling career was over",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-42",
      text: "Are you a dog person because",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-43",
      text: "Caught in the act",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-44",
      text: "Don't show this to my mom",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-45",
      text: "Caption this photo",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-46",
      text: "Video most likely to win an Oscar",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-47",
      text: "I feel famous when",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-48",
      text: "Most exotic place I've been",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-49",
      text: "Guess where this photo was taken",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-50",
      text: "Don't judge me",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-51",
      text: "Post-coffee me",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-52",
      text: "You had to be there",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-53",
      text: "#MondaysAmIRight?",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-54",
      text: "Take me back to",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-55",
      text: "The advertisement for my life would look like",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-56",
      text: "Guess how many takes this took",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-57",
      text: "My submission to National Geographic",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-58",
      text: "Plandid or candid?",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-59",
      text: "Let me introduce you to my alter ego",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-60",
      text: "My proudest moment",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-61",
      text: "This could be us",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-62",
      text: "A favorite memory of mine",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-63",
      text: "This should go viral",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-64",
      text: "Me and my best friend",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-65",
      text: "It was all fun and games until",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-66",
      text: "Thank you for coming to my TED Talk",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-67",
      text: "Woke up like this",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-68",
      text: "Pre-coffee me",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-69",
      text: "Write the subtitles for this video",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-70",
      text: "How I fight the Sunday scaries",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-71",
      text: "Who wore it better?",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
    {
      id: "hinge-caption-72",
      text: "Comment if you've been here",
      type: "text",
      source: "HINGE",
      category: "Photo Captions",
    },
  ],
};

// Helper functions
export function getPromptsByApp(app: "TINDER" | "HINGE"): Prompt[] {
  return PROMPT_BANK[app] || [];
}

export function getAllPrompts(): Prompt[] {
  return [...PROMPT_BANK.TINDER, ...PROMPT_BANK.HINGE];
}

export function getPromptById(id: string): Prompt | undefined {
  return getAllPrompts().find((p) => p.id === id);
}

export function getPromptsByCategory(category: string): Prompt[] {
  return getAllPrompts().filter((p) => p.category === category);
}

export function getCategories(): string[] {
  const categories = new Set(
    getAllPrompts()
      .map((p) => p.category)
      .filter(Boolean),
  );
  return Array.from(categories) as string[];
}
